/*
 * HEI Admin API
 * _Programmatically connect to a computer programming [school](https://hei.school)._ After [joining us](mailto:contact@hei.school), you can get an identification token from our [dev](https://dev-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=5s8cg50doahmu855rlc8fr6qmp&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-dev.hei.school%2Fwhoami) or [prod](https://prod-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=i8bg538jpfu6mqmqb61m26trd&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-prod.hei.school%2Fwhoami) authentication service. Then, start playing with our system!  The implementation of our API is [publicly disclosed](https://github.com/hei-school/hei-admin-api). You are welcome to try and compromise it. Happy hacking!
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;

/** CreateFee */
@JsonPropertyOrder({
  CreateFee.JSON_PROPERTY_TYPE,
  CreateFee.JSON_PROPERTY_COMMENT,
  CreateFee.JSON_PROPERTY_TOTAL_AMOUNT,
  CreateFee.JSON_PROPERTY_CREATION_DATETIME,
  CreateFee.JSON_PROPERTY_DUE_DATETIME
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-04-12T05:04:27.816360125+03:00[Indian/Antananarivo]",
    comments = "Generator version: 7.6.0")
public class CreateFee {
  /** Gets or Sets type */
  public enum TypeEnum {
    TUITION("TUITION"),

    HARDWARE("HARDWARE");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private String comment;

  public static final String JSON_PROPERTY_TOTAL_AMOUNT = "total_amount";
  private Integer totalAmount;

  public static final String JSON_PROPERTY_CREATION_DATETIME = "creation_datetime";
  private java.time.Instant creationDatetime;

  public static final String JSON_PROPERTY_DUE_DATETIME = "due_datetime";
  private java.time.Instant dueDatetime;

  public CreateFee() {}

  public CreateFee type(TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TypeEnum getType() {
    return type;
  }

  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }

  public CreateFee comment(String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Get comment
   *
   * @return comment
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getComment() {
    return comment;
  }

  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(String comment) {
    this.comment = comment;
  }

  public CreateFee totalAmount(Integer totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

  /**
   * Get totalAmount
   *
   * @return totalAmount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalAmount() {
    return totalAmount;
  }

  @JsonProperty(JSON_PROPERTY_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalAmount(Integer totalAmount) {
    this.totalAmount = totalAmount;
  }

  public CreateFee creationDatetime(java.time.Instant creationDatetime) {
    this.creationDatetime = creationDatetime;
    return this;
  }

  /**
   * Get creationDatetime
   *
   * @return creationDatetime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATION_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public java.time.Instant getCreationDatetime() {
    return creationDatetime;
  }

  @JsonProperty(JSON_PROPERTY_CREATION_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationDatetime(java.time.Instant creationDatetime) {
    this.creationDatetime = creationDatetime;
  }

  public CreateFee dueDatetime(java.time.Instant dueDatetime) {
    this.dueDatetime = dueDatetime;
    return this;
  }

  /**
   * Get dueDatetime
   *
   * @return dueDatetime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DUE_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public java.time.Instant getDueDatetime() {
    return dueDatetime;
  }

  @JsonProperty(JSON_PROPERTY_DUE_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDueDatetime(java.time.Instant dueDatetime) {
    this.dueDatetime = dueDatetime;
  }

  /** Return true if this CreateFee object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateFee createFee = (CreateFee) o;
    return Objects.equals(this.type, createFee.type)
        && Objects.equals(this.comment, createFee.comment)
        && Objects.equals(this.totalAmount, createFee.totalAmount)
        && Objects.equals(this.creationDatetime, createFee.creationDatetime)
        && Objects.equals(this.dueDatetime, createFee.dueDatetime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, comment, totalAmount, creationDatetime, dueDatetime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateFee {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    creationDatetime: ").append(toIndentedString(creationDatetime)).append("\n");
    sb.append("    dueDatetime: ").append(toIndentedString(dueDatetime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(
          String.format(
              "%stype%s=%s",
              prefix,
              suffix,
              URLEncoder.encode(String.valueOf(getType()), StandardCharsets.UTF_8)
                  .replaceAll("\\+", "%20")));
    }

    // add `comment` to the URL query string
    if (getComment() != null) {
      joiner.add(
          String.format(
              "%scomment%s=%s",
              prefix,
              suffix,
              URLEncoder.encode(String.valueOf(getComment()), StandardCharsets.UTF_8)
                  .replaceAll("\\+", "%20")));
    }

    // add `total_amount` to the URL query string
    if (getTotalAmount() != null) {
      joiner.add(
          String.format(
              "%stotal_amount%s=%s",
              prefix,
              suffix,
              URLEncoder.encode(String.valueOf(getTotalAmount()), StandardCharsets.UTF_8)
                  .replaceAll("\\+", "%20")));
    }

    // add `creation_datetime` to the URL query string
    if (getCreationDatetime() != null) {
      joiner.add(
          String.format(
              "%screation_datetime%s=%s",
              prefix,
              suffix,
              URLEncoder.encode(String.valueOf(getCreationDatetime()), StandardCharsets.UTF_8)
                  .replaceAll("\\+", "%20")));
    }

    // add `due_datetime` to the URL query string
    if (getDueDatetime() != null) {
      joiner.add(
          String.format(
              "%sdue_datetime%s=%s",
              prefix,
              suffix,
              URLEncoder.encode(String.valueOf(getDueDatetime()), StandardCharsets.UTF_8)
                  .replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}
