/*
 * HEI Admin API
 * _Programmatically connect to a computer programming [school](https://hei.school)._ After [joining us](mailto:contact@hei.school), you can get an identification token from our [dev](https://dev-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=5s8cg50doahmu855rlc8fr6qmp&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-dev.hei.school%2Fwhoami) or [prod](https://prod-hei-admin.auth.eu-west-3.amazoncognito.com/oauth2/authorize?client_id=i8bg538jpfu6mqmqb61m26trd&response_type=token&scope=email+openid&redirect_uri=https%3A%2F%2Fapi-prod.hei.school%2Fwhoami) authentication service. Then, start playing with our system!  The implementation of our API is [publicly disclosed](https://github.com/hei-school/hei-admin-api). You are welcome to try and compromise it. Happy hacking!
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;
import com.example.demo.client.model.Course;
import com.example.demo.client.model.CrupdateCourse;
import com.example.demo.client.model.Group;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.StringJoiner;
import java.util.function.Consumer;

@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-04-12T05:04:27.816360125+03:00[Indian/Antananarivo]",
    comments = "Generator version: 7.6.0")
public class TeachingApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public TeachingApi() {
    this(new ApiClient());
  }

  public TeachingApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response)
      throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create new groups or update existing groups Update groups when &#x60;id&#x60; are provided,
   * create them otherwise.
   *
   * @param group Groups to update (required)
   * @return List&lt;Group&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Group> createOrUpdateGroups(List<Group> group) throws ApiException {
    ApiResponse<List<Group>> localVarResponse = createOrUpdateGroupsWithHttpInfo(group);
    return localVarResponse.getData();
  }

  /**
   * Create new groups or update existing groups Update groups when &#x60;id&#x60; are provided,
   * create them otherwise.
   *
   * @param group Groups to update (required)
   * @return ApiResponse&lt;List&lt;Group&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Group>> createOrUpdateGroupsWithHttpInfo(List<Group> group)
      throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createOrUpdateGroupsRequestBuilder(group);
    try {
      HttpResponse<InputStream> localVarResponse =
          memberVarHttpClient.send(
              localVarRequestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode() / 100 != 2) {
          throw getApiException("createOrUpdateGroups", localVarResponse);
        }
        return new ApiResponse<List<Group>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            localVarResponse.body() == null
                ? null
                : memberVarObjectMapper.readValue(
                    localVarResponse.body(),
                    new TypeReference<List<Group>>() {}) // closes the InputStream
            );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createOrUpdateGroupsRequestBuilder(List<Group> group)
      throws ApiException {
    // verify the required parameter 'group' is set
    if (group == null) {
      throw new ApiException(
          400, "Missing the required parameter 'group' when calling createOrUpdateGroups");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/groups";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(group);
      localVarRequestBuilder.method(
          "PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Crupdate courses Update courses when id are provided, create them otherwise.
   *
   * @param crupdateCourse (required)
   * @return List&lt;Course&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Course> crupdateCourses(List<CrupdateCourse> crupdateCourse) throws ApiException {
    ApiResponse<List<Course>> localVarResponse = crupdateCoursesWithHttpInfo(crupdateCourse);
    return localVarResponse.getData();
  }

  /**
   * Crupdate courses Update courses when id are provided, create them otherwise.
   *
   * @param crupdateCourse (required)
   * @return ApiResponse&lt;List&lt;Course&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Course>> crupdateCoursesWithHttpInfo(List<CrupdateCourse> crupdateCourse)
      throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateCoursesRequestBuilder(crupdateCourse);
    try {
      HttpResponse<InputStream> localVarResponse =
          memberVarHttpClient.send(
              localVarRequestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode() / 100 != 2) {
          throw getApiException("crupdateCourses", localVarResponse);
        }
        return new ApiResponse<List<Course>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            localVarResponse.body() == null
                ? null
                : memberVarObjectMapper.readValue(
                    localVarResponse.body(),
                    new TypeReference<List<Course>>() {}) // closes the InputStream
            );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateCoursesRequestBuilder(List<CrupdateCourse> crupdateCourse)
      throws ApiException {
    // verify the required parameter 'crupdateCourse' is set
    if (crupdateCourse == null) {
      throw new ApiException(
          400, "Missing the required parameter 'crupdateCourse' when calling crupdateCourses");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateCourse);
      localVarRequestBuilder.method(
          "PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get course by identifier
   *
   * @param id (required)
   * @return Course
   * @throws ApiException if fails to make API call
   */
  public Course getCourseById(String id) throws ApiException {
    ApiResponse<Course> localVarResponse = getCourseByIdWithHttpInfo(id);
    return localVarResponse.getData();
  }

  /**
   * Get course by identifier
   *
   * @param id (required)
   * @return ApiResponse&lt;Course&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Course> getCourseByIdWithHttpInfo(String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCourseByIdRequestBuilder(id);
    try {
      HttpResponse<InputStream> localVarResponse =
          memberVarHttpClient.send(
              localVarRequestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode() / 100 != 2) {
          throw getApiException("getCourseById", localVarResponse);
        }
        return new ApiResponse<Course>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            localVarResponse.body() == null
                ? null
                : memberVarObjectMapper.readValue(
                    localVarResponse.body(),
                    new TypeReference<Course>() {}) // closes the InputStream
            );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCourseByIdRequestBuilder(String id) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getCourseById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses/{id}".replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all courses
   *
   * @param page Set value to 1 by default if null is provided (optional)
   * @param pageSize Set value to 15 by default if null is provided (optional)
   * @param code Filter course by code, case is ignored (optional)
   * @param name Filter course by name, case is ignored (optional)
   * @param credits Filter course by credits, case is ignored (optional)
   * @param teacherFirstName Filter course by teacher first name, case is ignored (optional)
   * @param teacherLastName Filter course by teacher last name, case is ignored (optional)
   * @param creditsOrder Order by credits. Can be DESC or ASC (optional)
   * @param codeOrder Order by code. Can be DESC or ASC (optional)
   * @return List&lt;Course&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Course> getCourses(
      Integer page,
      Integer pageSize,
      String code,
      String name,
      String credits,
      String teacherFirstName,
      String teacherLastName,
      String creditsOrder,
      String codeOrder)
      throws ApiException {
    ApiResponse<List<Course>> localVarResponse =
        getCoursesWithHttpInfo(
            page,
            pageSize,
            code,
            name,
            credits,
            teacherFirstName,
            teacherLastName,
            creditsOrder,
            codeOrder);
    return localVarResponse.getData();
  }

  /**
   * Get all courses
   *
   * @param page Set value to 1 by default if null is provided (optional)
   * @param pageSize Set value to 15 by default if null is provided (optional)
   * @param code Filter course by code, case is ignored (optional)
   * @param name Filter course by name, case is ignored (optional)
   * @param credits Filter course by credits, case is ignored (optional)
   * @param teacherFirstName Filter course by teacher first name, case is ignored (optional)
   * @param teacherLastName Filter course by teacher last name, case is ignored (optional)
   * @param creditsOrder Order by credits. Can be DESC or ASC (optional)
   * @param codeOrder Order by code. Can be DESC or ASC (optional)
   * @return ApiResponse&lt;List&lt;Course&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Course>> getCoursesWithHttpInfo(
      Integer page,
      Integer pageSize,
      String code,
      String name,
      String credits,
      String teacherFirstName,
      String teacherLastName,
      String creditsOrder,
      String codeOrder)
      throws ApiException {
    HttpRequest.Builder localVarRequestBuilder =
        getCoursesRequestBuilder(
            page,
            pageSize,
            code,
            name,
            credits,
            teacherFirstName,
            teacherLastName,
            creditsOrder,
            codeOrder);
    try {
      HttpResponse<InputStream> localVarResponse =
          memberVarHttpClient.send(
              localVarRequestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode() / 100 != 2) {
          throw getApiException("getCourses", localVarResponse);
        }
        return new ApiResponse<List<Course>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            localVarResponse.body() == null
                ? null
                : memberVarObjectMapper.readValue(
                    localVarResponse.body(),
                    new TypeReference<List<Course>>() {}) // closes the InputStream
            );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCoursesRequestBuilder(
      Integer page,
      Integer pageSize,
      String code,
      String name,
      String credits,
      String teacherFirstName,
      String teacherLastName,
      String creditsOrder,
      String codeOrder)
      throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/courses";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));
    localVarQueryParameterBaseName = "code";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("code", code));
    localVarQueryParameterBaseName = "name";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("name", name));
    localVarQueryParameterBaseName = "credits";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("credits", credits));
    localVarQueryParameterBaseName = "teacher_first_name";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("teacher_first_name", teacherFirstName));
    localVarQueryParameterBaseName = "teacher_last_name";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("teacher_last_name", teacherLastName));
    localVarQueryParameterBaseName = "creditsOrder";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("creditsOrder", creditsOrder));
    localVarQueryParameterBaseName = "codeOrder";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("codeOrder", codeOrder));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(
          URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get group by identifier
   *
   * @param id (required)
   * @return Group
   * @throws ApiException if fails to make API call
   */
  public Group getGroupById(String id) throws ApiException {
    ApiResponse<Group> localVarResponse = getGroupByIdWithHttpInfo(id);
    return localVarResponse.getData();
  }

  /**
   * Get group by identifier
   *
   * @param id (required)
   * @return ApiResponse&lt;Group&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Group> getGroupByIdWithHttpInfo(String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getGroupByIdRequestBuilder(id);
    try {
      HttpResponse<InputStream> localVarResponse =
          memberVarHttpClient.send(
              localVarRequestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode() / 100 != 2) {
          throw getApiException("getGroupById", localVarResponse);
        }
        return new ApiResponse<Group>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            localVarResponse.body() == null
                ? null
                : memberVarObjectMapper.readValue(
                    localVarResponse.body(),
                    new TypeReference<Group>() {}) // closes the InputStream
            );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getGroupByIdRequestBuilder(String id) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getGroupById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/groups/{id}".replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all groups
   *
   * @return List&lt;Group&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Group> getGroups() throws ApiException {
    ApiResponse<List<Group>> localVarResponse = getGroupsWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * Get all groups
   *
   * @return ApiResponse&lt;List&lt;Group&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Group>> getGroupsWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getGroupsRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse =
          memberVarHttpClient.send(
              localVarRequestBuilder.build(), HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode() / 100 != 2) {
          throw getApiException("getGroups", localVarResponse);
        }
        return new ApiResponse<List<Group>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            localVarResponse.body() == null
                ? null
                : memberVarObjectMapper.readValue(
                    localVarResponse.body(),
                    new TypeReference<List<Group>>() {}) // closes the InputStream
            );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getGroupsRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/groups";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
}
