# Identifiant unique du projet
sonar.projectKey=votre-projet-key
sonar.projectName=Votre Projet
sonar.projectVersion=1.0

# Sources
sonar.sources=src/main/java
sonar.tests=src/test/java

# Langage
sonar.language=java
sonar.java.source=21

# Exclusions
sonar.exclusions=**/client/**, **/model/**, **/dto/**, **/config/**

# Rapports de couverture
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/jacocoTestReport.xml

# Rapports Checkstyle
sonar.java.checkstyle.reportPaths=build/reports/checkstyle/main.xml